sudo: required
dist: precise
language: cpp

env:
  global:
  - LANG="en_US.UTF-8"

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
            - postgresql-server-dev-all
      env: COMPILER=g++-4.9

before_install:
  - sudo apt-get update -qq

install:
  # install cmake
  - CMAKE_VERSION="3.5.2"
  - wget --no-check-certificate "http://cmake.org/files/v3.5/cmake-${CMAKE_VERSION}-Linux-x86_64.sh"
  - chmod +x cmake-${CMAKE_VERSION}-Linux-x86_64.sh
  - ./cmake-${CMAKE_VERSION}-Linux-x86_64.sh --prefix=`pwd` --skip-license
  - export PATH=~/bin:$PATH
  # verify installed versions
  - which cmake
  - cmake --version

script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_CXX_COMPILER=$COMPILER .. && make
  - ./postgres-test
