sudo: required
dist: precise
language: cpp

env:
  global:
  - LANG="en_US.UTF-8"

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports
          packages:
            - g++-4.9
            - cmake
            - cmake-data
      env: COMPILER=g++-4.9

before_install:
  - sudo apt-get update -qq

script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_CXX_COMPILER=$COMPILER .. && make
