image:
- Visual Studio 2015

platform:
- x64

configuration:
- Debug
- Release

environment:
  BOOST_FILENAME_VERSION: 1_63_0
  BOOST_VERSION: 1.63.0
  BOOST_ROOT: "C:\\Libraries\\boost_1_63_0"
  BOOST_LIBRARYDIR: "C:\\Libraries\\boost_1_63_0\\lib64-msvc-14.0"

build_script:
  - mkdir build
  - cd build
  - cmake -G "Visual Studio 14 2015 Win64" ..
