init:
  # - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

on_finish:
  # - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

image:
- Visual Studio 2015

platform:
- x64

configuration:
- Debug
- Release

environment:
  APPVEYOR_RDP_PASSWORD: eyJJV4MXNmZ
  BOOST_FILENAME_VERSION: 1_63_0
  BOOST_VERSION: 1.63.0
  BOOST_ROOT: "C:\\Libraries\\boost_1_63_0"
  BOOST_LIBRARYDIR: "C:\\Libraries\\boost_1_63_0\\lib64-msvc-14.0"
  GTEST_VERSION: 1.7.0

before_build:
  - git clone https://github.com/google/googletest.git
  - cd googletest
  - git checkout tags/release-%GTEST_VERSION%
  - cmake -G "Visual Studio 14 2015 Win64" -DBUILD_SHARED_LIBS=ON -Dgtest_force_shared_crt=ON .
  - msbuild gtest.sln
  - move %CONFIGURATION% lib
  - cd ..
  - curl -L -o postgresql-9.5.3.tar.gz https://ftp.postgresql.org/pub/source/v9.5.3/postgresql-9.5.3.tar.gz
  - cmake -E tar -zxf postgresql-9.5.3.tar.gz
  - cd postgresql-9.5.3\src\interfaces\libpq
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x64
  - 'nmake /f win32.mak CPU=AMD64 && exit 0'
  - mkdir C:\projects\libpq\include\internal
  - mkdir C:\projects\libpq\lib
  - copy libpq-int.h C:\projects\libpq\include\internal
  - copy pqexpbuffer.h C:\projects\libpq\include\internal
  - copy libpq-events.h C:\projects\libpq\include
  - copy libpq-fe.h C:\projects\libpq\include
  - copy Release\*.lib C:\projects\libpq\lib

services:
  - postgresql

build_script:
  - cd  C:\projects\libpqmxx
  - mkdir build
  - cd build
  - cmake -G "Visual Studio 14 2015 Win64" -DGTEST_ROOT=C:\projects\libpqmxx\googletest -DPostgreSQL_ROOT=C:\projects\libpq ..
  - msbuild postgres-test.sln
  - echo %PATH%
  - set PATH=C:\projects\libpqmxx\googletest\lib;%PATH%
  - set PATH=C:\Libraries\boost_1_63_0\lib64-msvc-14.0;%PATH%
#  - set PATH=C:\Program Files\PostgreSQL\9.6\lib;%PATH%
#  - curl -L -o C:\projects\libpqmxx\build\%CONFIGURATION%\libintl-8.dll https://github.com/maxwell-k/libintl-appveyor/releases/download/gettext-0.19.7%2B1/libintl-8.dll
  - C:\projects\libpqmxx\build\%CONFIGURATION%\postgres-test.exe

# before_test:
#  - psql -c 'create user "ci-test";'
#  - psql -c 'create database "ci-test" OWNER "ci-test" ENCODING '"'"'UTF8'"'"';'

# test_script:
