init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

image:
- Visual Studio 2015

platform:
- x64

configuration:
- Debug
- Release

environment:
  APPVEYOR_RDP_PASSWORD: eyJJV4MXNmZ
  BOOST_FILENAME_VERSION: 1_63_0
  BOOST_VERSION: 1.63.0
  BOOST_ROOT: "C:\\Libraries\\boost_1_63_0"
  BOOST_LIBRARYDIR: "C:\\Libraries\\boost_1_63_0\\lib64-msvc-14.0"
  GTEST_VERSION: 1.7.0

before_build:
  - git clone https://github.com/google/googletest.git
  - cd googletest
  - git checkout tags/release-%GTEST_VERSION%
  - cmake -G "Visual Studio 14 2015 Win64" -DBUILD_SHARED_LIBS=ON -Dgtest_force_shared_crt=ON .
  - msbuild gtest.sln
  - move %CONFIGURATION% lib

services:
  - postgresql

build_script:
  - cd  C:\projects\libpqmxx
  - mkdir build
  - cd build
  - cmake -G "Visual Studio 14 2015 Win64" -D GTEST_ROOT=C:\projects\libpqmxx\googletest ..
  - msbuild postgres-test.sln
  - echo %PATH%
  - set PATH=C:\projects\libpqmxx\googletest\lib;%PATH%
  - set PATH=C:\Libraries\boost_1_63_0\lib64-msvc-14.0;%PATH%
  - echo %PATH%
  - dir C:\Libraries\boost_1_63_0\lib64-msvc-14.0
  - C:\projects\libpqmxx\build\%CONFIGURATION%\postgres-test.exe

# before_test:
#  - psql -c 'create user "ci-test";'
#  - psql -c 'create database "ci-test" OWNER "ci-test" ENCODING '"'"'UTF8'"'"';'

# test_script:
