image:
- Visual Studio 2015

platform:
- x64

configuration:
- Debug
- Release

environment:
  BOOST_FILENAME_VERSION: 1_63_0
  BOOST_VERSION: 1.63.0
  BOOST_ROOT: "C:\\Libraries\\boost_1_63_0"
  BOOST_LIBRARYDIR: "C:\\Libraries\\boost_1_63_0\\lib64-msvc-14.0"
  LIB_GTEST_VERSION: 1.7.0

before_build:
  - git clone https://github.com/google/googletest.git
  - git checkout tags/release-1.7.0
  - cd googletest
  - cmake -DBUILD_SHARED_LIBS=ON -Dgtest_force_shared_crt=ON .
  - dir

services:
  - postgresql

build_script:
  - mkdir build
  - cd build
  - cmake -G "Visual Studio 14 2015 Win64" ..
